"""Kokoro TTS voiceover generator for Remotion reels.

Usage (from the remotion/ folder):
  .tts/Scripts/python tools/voiceover.py --script public/reels/<slug>/vo.json --out public/reels/<slug>/vo \
      [--voice af_heart] [--lang a] [--speed 1.0] [--ts src/reels/<slug>/vo-timings.ts]

vo.json is either {"key": "line text", ...} or [{"key": "...", "text": "..."}, ...].
Fix pronunciation inline with phonemes, e.g. [SEO](/ˌɛsˌiˈO/), [demos](/ˈdɛmOz/), [AI](/ˌAˈI/).

Writes one loudness-normalized WAV per line (<key>.wav, -16 LUFS, 48 kHz), plus timings.json with each
line's duration and word start/end times. --ts also writes the same data as a TypeScript module for the reel.
"""

import argparse
import json
import re
import subprocess
from pathlib import Path

import numpy as np
import soundfile as sf
from kokoro import KPipeline

SR = 24000
WORD = re.compile(r"[A-Za-z0-9]")


def load_lines(path: Path):
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        return list(data.items())
    return [(item["key"], item["text"]) for item in data]


def render(pipe, text, voice, speed):
    audio, words, offset = [], [], 0.0
    for result in pipe(text, voice=voice, speed=speed):
        chunk = np.asarray(result.audio, dtype=np.float32)
        for tok in result.tokens or []:
            if WORD.search(tok.text or "") and tok.start_ts is not None:
                words.append({"text": tok.text, "start": offset + tok.start_ts, "end": offset + (tok.end_ts or tok.start_ts)})
        audio.append(chunk)
        offset += len(chunk) / SR
    return np.concatenate(audio), words


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--voice", default="af_heart")
    ap.add_argument("--lang", default="a", help="a = American English, b = British English")
    ap.add_argument("--speed", default=1.0, type=float)
    ap.add_argument("--ts", type=Path, help="optional path for a TypeScript timings module")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    pipe = KPipeline(lang_code=args.lang, repo_id="hexgrad/Kokoro-82M")
    out = {}
    for key, text in load_lines(args.script):
        wav, words = render(pipe, text, args.voice, args.speed)
        idx = np.where(np.abs(wav) > 0.01)[0]
        lead = max(idx[0] - int(0.03 * SR), 0) if len(idx) else 0
        tail = idx[-1] + int(0.12 * SR) if len(idx) else len(wav)
        wav = wav[lead:tail]
        shift = lead / SR
        raw = args.out / f"{key}.raw.wav"
        sf.write(raw, wav, SR)
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(raw),
             "-af", "loudnorm=I=-16:TP=-1.5:LRA=7", "-ar", "48000", str(args.out / f"{key}.wav")],
            check=True,
        )
        raw.unlink()
        out[key] = {
            "duration": round(len(wav) / SR, 3),
            "words": [
                {"text": w["text"], "start": round(max(w["start"] - shift, 0), 3), "end": round(max(w["end"] - shift, 0), 3)}
                for w in words
            ],
        }
        print(f"{key}: {out[key]['duration']}s, {len(words)} words", flush=True)

    (args.out / "timings.json").write_text(json.dumps({"voice": args.voice, "lines": out}, indent=2), encoding="utf-8")
    if args.ts:
        args.ts.parent.mkdir(parents=True, exist_ok=True)
        args.ts.write_text(
            f"// Generated by tools/voiceover.py ({args.voice}). Do not edit by hand.\n"
            f"export const VO = {json.dumps(out, indent=2)} as const;\n\nexport type VoKey = keyof typeof VO;\n",
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()
